name: sedkit-3.7

channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- pip
- python==3.7.1
- pip:
  - astropy==4.3.1
  - astroquery==0.4.2
  - bokeh>=2.2.3
  - dill==0.3.4
  - dustmaps==1.0.9
  - emcee>=3.1.1
  - ipython==8.2.0
  - jupyter==1.0.0
  - numpy>=1.21.5
  - pandas>=1.3.5
  - pickle5>=0.0.11
  - pytest==7.1.1
  - sphinx==4.5.0
  - scipy==1.8.0
  - svo-filters==0.4.1
